"""empty message

Revision ID: 1802444a5cdf
Revises: 125c1c425dd4
Create Date: 2021-06-15 05:29:46.451642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1802444a5cdf'
down_revision = '125c1c425dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('coming_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'coming_show')
    # ### end Alembic commands ###
