"""empty message

Revision ID: 892cae3e3f56
Revises: 1802444a5cdf
Create Date: 2021-06-16 03:47:06.577646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892cae3e3f56'
down_revision = '1802444a5cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'coming_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('coming_show', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
